import { Post } from '@/lib/types/post';

// Seed nguyên văn từ seedState.products trong open_design/js/app.js (posts p1–p6).
export const seedPosts: Post[] = [
  {
    id: 'p1',
    title: 'Máy tính Casio fx-580VN X',
    icon: '∑',
    type: 'Sale',
    price: 280000,
    category: 'Study electronics',
    owner: 'Nguyễn Minh An',
    ownerRole: 'Student',
    status: 'Approved',
    date: '2026-05-24',
    content:
      'Mình bán lại máy tính Casio fx-580VN X còn dùng tốt. Phù hợp cho các bạn lớp 10–12 cần máy tính để học Toán và Lý.',
    description:
      'Máy tính còn tốt, đủ nắp trượt, phím bấm ổn định, có vài vết xước nhẹ ở mặt sau.',
    contact: 'an@student.school.edu',
    items: [{ name: 'Máy tính Casio fx-580VN X', category: 'Study electronics', price: 280000, condition: 'used_good' as const, imageName: '∑' }],
  },
  {
    id: 'p2',
    title: 'Bộ sách giáo khoa lớp 10',
    icon: 'BOOK',
    type: 'Donation',
    price: 0,
    category: 'Books',
    owner: 'Trần Thị Mai',
    ownerRole: 'Teacher',
    status: 'Approved',
    campaignId: 'c1',
    campaignName: 'Góc học tập cho học sinh mới',
    date: '2026-05-21',
    content:
      'Cô gửi tặng bộ sách giáo khoa lớp 10 cho campaign Góc học tập cho học sinh mới. Sách đã bọc bìa và vẫn còn dùng tốt.',
    description:
      'Bộ sách đã bọc bìa, có ghi chú nhẹ ở vài trang, phù hợp cho học sinh mới nhập học.',
    contact: 'mai@school.edu',
    items: [{ name: 'Bộ sách giáo khoa lớp 10', category: 'Books', price: 0, condition: 'used_normal' as const, imageName: 'BOOK' }],
  },
  {
    id: 'p3',
    title: 'Áo đồng phục size M',
    icon: 'UNI',
    type: 'Exchange',
    price: 0,
    category: 'Uniforms',
    owner: 'Nguyễn Minh An',
    ownerRole: 'Student',
    status: 'Approved',
    date: '2026-05-18',
    content:
      'Mình muốn đổi áo đồng phục size M sang size L. Áo đã giặt sạch, không rách, phù hợp bạn nào cần size M.',
    description: 'Muốn đổi sang size L, áo sạch và không rách.',
    contact: 'an@student.school.edu',
    items: [{ name: 'Áo đồng phục size M', category: 'Uniforms', price: 0, condition: 'used_good' as const, imageName: 'UNI' }],
  },
  {
    id: 'p4',
    title: 'Vợt cầu lông Yonex cũ',
    icon: 'RKT',
    type: 'Sale',
    price: 150000,
    category: 'Sports equipment',
    owner: 'Trần Thị Mai',
    ownerRole: 'Teacher',
    status: 'Approved',
    campaignId: 'c2',
    campaignName: 'Quỹ thể thao mùa hè',
    date: '2026-05-15',
    content:
      'Bán lại vợt cầu lông để đóng góp cho Quỹ thể thao mùa hè. Vợt đã thay dây mới, phù hợp cho CLB hoặc giờ thể dục.',
    description: 'Dây mới thay, tay cầm hơi cũ nhưng dùng ổn cho CLB.',
    contact: 'mai@school.edu',
    items: [{ name: 'Vợt cầu lông Yonex cũ', category: 'Sports equipment', price: 150000, condition: 'used_normal' as const, imageName: 'RKT' }],
  },
  {
    id: 'p5',
    title: 'Đèn bàn học chống cận',
    icon: 'LAMP',
    type: 'Sale',
    price: 90000,
    category: 'School supplies',
    owner: 'Nguyễn Minh An',
    ownerRole: 'Student',
    status: 'Pending Approval',
    campaignId: 'c1',
    campaignName: 'Góc học tập cho học sinh mới',
    date: '2026-06-01',
    content:
      'Mình muốn đưa đèn LED ba mức sáng vào campaign Góc học tập cho học sinh mới. Đèn còn sáng tốt và phù hợp góc học tập.',
    description: 'Đèn LED ba mức sáng, phù hợp góc học tập.',
    contact: 'an@student.school.edu',
    items: [{ name: 'Đèn bàn học chống cận', category: 'School supplies', price: 90000, condition: 'used_good' as const, imageName: 'LAMP' }],
  },
  {
    id: 'p6',
    title: 'Ba lô đi học màu xanh',
    icon: 'BAG',
    type: 'Donation',
    price: 0,
    category: 'Other allowed items',
    owner: 'Trần Thị Mai',
    ownerRole: 'Teacher',
    status: 'Rejected',
    date: '2026-05-10',
    content:
      'Cô muốn quyên góp một ba lô màu xanh còn dùng được cho học sinh cần hỗ trợ.',
    description: 'Balo còn dùng được, dây kéo cần vệ sinh.',
    contact: 'mai@school.edu',
    reason: 'Ảnh chưa đủ rõ tình trạng sản phẩm.',
    items: [{ name: 'Ba lô đi học màu xanh', category: 'Other allowed items', price: 0, condition: 'old' as const, imageName: 'BAG' }],
  },
];
